--- Makefile
+++ Makefile
@@ -384,6 +396,12 @@
 		   -fno-strict-aliasing -fno-common \
 		   -Werror-implicit-function-declaration \
 		   -Wno-format-security \
+                   -marm -mfloat-abi=softfp -march=armv7-a \
+                   -mfpu=neon-fp16 -ffast-math -pipe \
+                   -funswitch-loops -fpredictive-commoning -fgcse-after-reload -fno-tree-vectorize \
+                   -ftree-vectorize -funsafe-math-optimizations \
+                   -fsched-spec-load -mvectorize-with-neon-quad \
+                   -fmodulo-sched -fmodulo-sched-allow-regmoves \
 		   -fno-delete-null-pointer-checks -Wno-array-bounds -Wno-maybe-uninitialized
 KBUILD_AFLAGS_KERNEL :=
 KBUILD_CFLAGS_KERNEL :=
